#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build XCArchive

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        description: 'The version number of the framework embedded in the XCArchives.'
        type: string
        required: true

jobs:
  create-xcframework-and-release-workflow:
    uses: StanfordBDHG/.github/.github/workflows/xcframework.yml@v2
    with:
      workspaceFile: llama.xcworkspace
      xcFrameworkName: llama
      scheme: llama
      sdk: '["iphoneos", "iphonesimulator", "macosx", "xros", "xrsimulator"]'
      version: 0.1.0
      configuration: Release
      runsonlabels: '["macOS", "self-hosted"]'
      user: PaulsAutomationBot
    secrets:
      access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}